[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://amd-fedor.tail73cba1.ts.net:8443/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
